<?php

namespace ContainerHjmV8Ce;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BpVrixuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bpVrixu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bpVrixu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'process_service' => ['privates', 'App\\Service\\ProcessService', 'getProcessServiceService', true],
        ], [
            'process_service' => 'App\\Service\\ProcessService',
        ]);
    }
}
