<?php

namespace ContainerVmtkdCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecuteProcessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ExecuteProcess' shared autowired service.
     *
     * @return \App\Command\ExecuteProcess
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ExecuteProcess.php';

        $container->privates['App\\Command\\ExecuteProcess'] = $instance = new \App\Command\ExecuteProcess();

        $instance->setName('app:execute-process');

        return $instance;
    }
}
