<?php

namespace ContainerVmtkdCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProcessService' shared autowired service.
     *
     * @return \App\Service\ProcessService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ProcessService.php';

        return $container->privates['App\\Service\\ProcessService'] = new \App\Service\ProcessService();
    }
}
