<?php

namespace ContainerBvbuCwI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultControlllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DefaultControlller' shared autowired service.
     *
     * @return \App\Controller\DefaultControlller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DefaultControlller.php';

        $container->services['App\\Controller\\DefaultControlller'] = $instance = new \App\Controller\DefaultControlller();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\DefaultControlller', $container));

        return $instance;
    }
}
