<?php

namespace ContainerV7JYxXM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddProcessControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AddProcessController' shared autowired service.
     *
     * @return \App\Controller\AddProcessController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/AddProcessController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Processes/Application/AddProcess.php';

        return $container->services['App\\Controller\\AddProcessController'] = new \App\Controller\AddProcessController(new \App\Service\Processes\Application\AddProcess(($container->privates['App\\Service\\Processes\\Infraestructure\\ProcesessDoctrineProxyRepository'] ?? $container->load('getProcesessDoctrineProxyRepositoryService'))));
    }
}
