<?php

namespace ContainerV7JYxXM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessDoctrineRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Processes\Infraestructure\ProcessDoctrineRepository' shared autowired service.
     *
     * @return \App\Service\Processes\Infraestructure\ProcessDoctrineRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Processes/Infraestructure/ProcessDoctrineRepository.php';

        return $container->privates['App\\Service\\Processes\\Infraestructure\\ProcessDoctrineRepository'] = new \App\Service\Processes\Infraestructure\ProcessDoctrineRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
