<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXUVxSJO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXUVxSJO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXUVxSJO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXUVxSJO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXUVxSJO\App_KernelDevDebugContainer([
    'container.build_hash' => 'XUVxSJO',
    'container.build_id' => '1c834605',
    'container.build_time' => 1628596992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXUVxSJO');
