<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NJkNO3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NJkNO3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2NJkNO3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2NJkNO3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2NJkNO3\App_KernelDevDebugContainer([
    'container.build_hash' => '2NJkNO3',
    'container.build_id' => 'fdd38395',
    'container.build_time' => 1628549547,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2NJkNO3');
