<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_defaultcontrolller_default' => [[], ['_controller' => 'App\\Controller\\DefaultControlller::default'], [], [['text', '/']], [], []],
    'app_process_all' => [[], ['_controller' => 'App\\Controller\\ProcessController::all'], [], [['text', '/api/process']], [], []],
    'app_process_add' => [[], ['_controller' => 'App\\Controller\\ProcessController::add'], [], [['text', '/api/process']], [], []],
    'app_process_start' => [['id_process'], ['_controller' => 'App\\Controller\\ProcessController::start'], [], [['text', '/start'], ['variable', '/', '[^/]++', 'id_process', true], ['text', '/api/process']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
